DDACCharityServices/DDACCharityServices/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DDACCharityServices.Data;
using DDACCharityServices.Models;

namespace DDACCharityServices.Controllers {
	public class DonationsController : Controller {
		private readonly DDACCharityServicesForBackgroundContext _context;

		public DonationsController(DDACCharityServicesForBackgroundContext context) {
			_context = context;
		}

		// GET: Donations
		public async Task<IActionResult> Index() {
			var donations = await _context.Donation.ToListAsync();
			foreach (Donation donation in donations) {
				donation.Background = await _context.Background.FindAsync(donation.BackgroundID);
			}
			return View(donations);
		}

		// GET: Donations/Details/5
		public async Task<IActionResult> Details(int? id) {
			if (id == null) return NotFound();

			var donation = await _context.Donation.FirstOrDefaultAsync(m => m.DonationID == id);
			if (donation == null) return NotFound();
			
			donation.Background = await _context.Background.FirstOrDefaultAsync(m => m.BackgroundID == donation.BackgroundID);
			return View(donation);
		}
	}
}

DDACCharityServices/DDACCharityServices/Controllers/UserListController.cs
using DDACCharityServices.Areas.Identity.Data;
using DDACCharityServices.Data;
using DDACCharityServices.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DDACCharityServices.Controllers
{
    public class UserListController : Controller
    {
        private readonly UserManager<DDACCharityServicesUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly DDACCharityServicesContext _context;

        public UserListController(
            DDACCharityServicesContext context,
            UserManager<DDACCharityServicesUser> userManager,
            RoleManager<IdentityRole> roleManager
        )
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(string searchstring, string searchkeyword)
        {
            var users = _userManager.Users;

            const string emailSearchKeyword = "Email";
            const string firstNameSearchKeyword = "First Name";
            const string lastNameSearchKeyword = "Last Name";
            const string roleSearchKeyword = "Role";

            var SearchKeywordList = new SelectList(
                    new List<SelectListItem>
                    {
                        new SelectListItem { Selected=true, Text="-", Value=""},
                        new SelectListItem { Selected=false, Text=emailSearchKeyword, Value=emailSearchKeyword},
                        new SelectListItem { Selected=false, Text=firstNameSearchKeyword, Value=firstNameSearchKeyword},
                        new SelectListItem { Selected=false, Text=lastNameSearchKeyword, Value=lastNameSearchKeyword},
                        new SelectListItem { Selected=false, Text=roleSearchKeyword, Value=roleSearchKeyword},
                    },
                    "Value", "Text", 1
                   );

            ViewBag.SearchKeywordList = SearchKeywordList;

            if (!string.IsNullOrEmpty(searchstring))
            {
                if (!string.IsNullOrEmpty(searchkeyword))
                {
                    switch (searchkeyword)
                    {
                        case emailSearchKeyword:
                            users = users.Where(user => user.Email.Contains(searchstring));
                            break;
                        case firstNameSearchKeyword:
                            users = users.Where(user => user.FirstName.Contains(searchstring));
                            break;
                        case lastNameSearchKeyword:
                            users = users.Where(user => user.LastName.Contains(searchstring));
                            break;
                    }
                }
            }

            var userList = new List<UserListModel>();
            if (searchkeyword == roleSearchKeyword)
            {
                if(!string.IsNullOrEmpty(searchstring))
                {
                    IList<DDACCharityServicesUser> roleusers = await _userManager.GetUsersInRoleAsync(searchstring);
                    foreach (DDACCharityServicesUser user in roleusers)
                    {
                        var currentUser = new UserListModel();
                        currentUser.CopyFromIdentityUser(user);
                        await currentUser.SetRoleFromIdentityUser(user, _userManager);
                        currentUser.FullImageUrl = user.profileImageUrl != null ? AWSHelper.GetFullImageUrl(user.profileImageUrl) : null;
                        userList.Add(currentUser);
                    }
                }
            } else
            {
                foreach (DDACCharityServicesUser user in users)
                {
                    var currentUser = new UserListModel();
                    currentUser.CopyFromIdentityUser(user);
                    await currentUser.SetRoleFromIdentityUser(user, _userManager);
                    currentUser.FullImageUrl = user.profileImageUrl != null ? AWSHelper.GetFullImageUrl(user.profileImageUrl) : null;
                    userList.Add(currentUser);
                }
            }

            return View(userList);
        }

        public IActionResult Create()
        {
            CustomUserModel user = new CustomUserModel();
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomUserModel model)
        {
            if (ModelState.IsValid)
            {
                var checkEmailExists = await _userManager.FindByEmailAsync(model.Email);

                if(checkEmailExists == null)
                {
                    bool roleExists = await _roleManager.RoleExistsAsync(model.UserRole);
                    if (!roleExists)
                    {
                        await _roleManager.CreateAsync(new IdentityRole(model.UserRole));
                    }

                    var user = new DDACCharityServicesUser
                    {
                        Email = model.Email,
                        UserName = model.Email,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        EmailConfirmed = true
                    };

                    var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, model.PhoneNumber);
                    var result = await _userManager.CreateAsync(user, model.Password);

                    if (result.Succeeded && setPhoneResult != null)
                    {
                        await _userManager.AddToRoleAsync(user, model.UserRole);

                        return RedirectToAction(nameof(Index));
                    } else
                    {
                        return View(model);
                    }
                } else
                {
                    TempData["message"] = $"Existing User!";
                    return View(model);
                }
            } else
            {
                return View(model);
            }
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var newUser = new CustomUpdateUserModel();
                newUser.CopyFromIdentityUser(user);
                await newUser.SetRoleFromIdentityUser(user, _userManager);
                return View(newUser);
            } else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CustomUpdateUserModel model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{model.Id}'.");
            }

            if (!ModelState.IsValid)
            {
                TempData["message"] = "The form is not valid! Please try again!";
                return View(model);
            }

            var phoneNumber = await _userManager.GetPhoneNumberAsync(user);
            if (model.PhoneNumber != phoneNumber)
            {
                var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, model.PhoneNumber);
                if (!setPhoneResult.Succeeded)
                {
                    TempData["message"] = "Unexpected error when trying to set phone number.";
                    return View(model);
                }
            }

            if (model.FirstName != user.FirstName)
            {
                user.FirstName = model.FirstName;
            }

            if (model.LastName != user.LastName)
            {
                user.LastName = model.LastName;
            }

            var currentUserRole = await _userManager.GetRolesAsync(user);

            bool roleExists = await _roleManager.RoleExistsAsync(model.UserRole);
            if (!roleExists)
            {
                await _roleManager.CreateAsync(new IdentityRole(model.UserRole));
            }

            if (currentUserRole.IndexOf(model.UserRole) == -1)
            {
                foreach(var role in currentUserRole)
                {
                    await _userManager.RemoveFromRoleAsync(user, role);
                }

                await _userManager.AddToRoleAsync(user, model.UserRole);
            }

            await _userManager.UpdateAsync(user);
            TempData["message"] = "Profile has been updated!";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var newUser = new CustomUserModel();
                newUser.CopyFromIdentityUser(user);
                await newUser.SetRoleFromIdentityUser(user, _userManager);
                return View(newUser);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

DDACCharityServices/DDACCharityServices/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using DDACCharityServices.Areas.Identity.Data

@inject SignInManager<DDACCharityServicesUser> SignInManager
@inject UserManager<DDACCharityServicesUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DDACCharityServices</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Charithese</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@

                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if (this.User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a id="manage" class="nav-link text-dark" asp-area="" asp-controller="UserList" asp-action="Index">Users</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a id="manage" class="nav-link text-dark" asp-area="" asp-controller="Backgrounds" asp-action="Index">Donation Backgrounds</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Donations" asp-action="Index">Donation History</a>
                            </li>
                        }
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DDACCharityServices - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>